### ISSUE TITLE
DICOM export unique UID

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#191]
Eclipse (and probably other TPSes) assumes that every new CT scan and every new VOI DICOM has new UID. After opening any DICOM in Eclipse it loads it and keeps it in its database for future reference.

Right now pyTRiP98 saves fixed UIDs to exported DICOMs. It means if you load in Eclipse DICOM file exported from pyTRiP then first file will load correctly. But when you take i.e. different CT cube, export it to DICOM then Eclipse import will fail - Eclipse will complain that DICOM with same UID already exists.

The way to solve that problem would be to generate unique UIDs, based for example on hashes from CTX and HED data. I think we should still assume that two identical CTX+HED sets leads to the same UIDs - generating UIDs based on timestamps doesn't make sense.

**Comment by nbassler** [comment]
what exactly is a UID?

**Comment by grzanka** [comment]
List of numbers separated by dots, identifying some objects in DICOM (i.e. CT scan).

**Comment by nbassler** [comment]
do you have a link to how UIDs are set?

**Comment by grzanka** [comment]
I haven't found a single place where this is described, DICOM documentation is needed.
See for inspiration https://github.com/pytrip/pytrip/pull/189/files#diff-ccb098b895b321aeff4106ea8eb155feR277

**Comment by nbassler** [comment]
@okejdokej says she will investigate later today

**Comment by okejdokej** [comment]
Dear All,

I suppose that, we want to create a value for the Tag "SeriesInstanceUID", because is the one that is required to be different, assuming that the idea is to "overwrite" some values of a given Dicom and create a new Dicom from it. Isn't it?
Then the Tag that has to be different is "SeriesInstanceUID",  this works for me. (I generate a "fake" PET and I load it into RayStation for the same patient and it works fine).

The idea is to be sure about uniqueness that is mandatory for DICOM standard, create a global uid (guid)

The UID consist on two parts <org id>.<guid>

- It seems that for the <org id>, the prefix '2.25.' can be 'safely' used.

- To generate the global uid (guid) I have found different ways:

1. Recommended in , http://dicom.nema.org/ , (part 5 appendix B): to use the method from [ISO/IEC 9834-8][ITU-T X.667], which provides a 'non official implementation' (annex D), for a time based uid generation. It is open software implemented in C (file:///C:/Users/user/Downloads/T-REC-X.667-201210-I!!PDF-E.pdf; page 34).

2. Simply to use a random (pseudo-random) guid generator such as uuid4 (import uuid; uuid.uuid4()); However it is necessary to take into account some encoding rules (http://dicom.nema.org/medical/dicom/current/output/pdf/part05.pdf; page 83)

´´´import uuid
     g = '%d' % (uuid.uuid4())
     dig=64 #-len('2.25.')  # I am not sure if dig should be just=64, I think the maximum length is 128... and every field should be less than 64.
     guid=g % (10 ** dig) #just to be sure that its length is less than 64 ...

3. Or use pydicom to write DICOM, they have been dealing with this issue also. However, it seems to me that they use uuid1() instead using uuid4(). (https://github.com/darcymason/pydicom/issues/125)

I don't know which option sounds correct to you in order to make 'pytrip' as self-contained as possible. I think that try option 1 is the best one, but option 2 should work in our cases, just trying to keep the rules given by NEMA 
(http://dicom.nema.org/medical/dicom/current/output/pdf/part05.pdf; page 83 and 105)

Best regards,
Okejdokey

**Comment by nbassler** [comment]
so what follows the '2.25.' prefix is the suffix and may not be longer than 64 integers?

```
import uuid
uidstr = '2.25.' + str(uuid.uuid4().int)[:64]
print(uidstr)
2.25.177036547486585879967707862627578808820
```
right?

**Comment by grzanka** [comment]
Another question to other users - what do you think about uniqueness of UIDs.

Let us assume we have 1.hed + 1.ctx. We convert it to DICOM and have some UIDs.
If two days later we convert it again should we get the same UID or it may be different ?

If UID generation is based on pseudorandom numbers (+ seed based on time) then we'd get different UIDs in abovementioned case.

I was thinking about pseudorandom generator with seed based on hashsum of .hed+.ctx files.
In such case converting the same files many times we will preserve UIDs. Different .hed+.ctx will lead to different UIDs (as hashsum and seed will be different).

**Comment by okejdokej** [comment]
nbassler, I am not sure. 
This is the definition of the UID (page 44, http://dicom.nema.org/medical/dicom/current/output/pdf/part05.pdf ):
" _A character string containing a UID that is used to uniquely identify​ a wide variety of items. The UID is a series of numeric components​ separated by the period "." character. If a Value Field containing​ one or more UIDs is an odd number of bytes in length, the Value​ Field shall be padded with a single trailing NULL (00H) character​ to ensure that the Value Field is an even number of bytes in length.
**Length of value**: 64 bytes maximum​_"
(However, I have read that UID in DICOM can be longer. Maybe we can try the actual maximum length after set the code)

grzanka, 
Once a patient´s Dicom is loaded in the planning system it is not possible to load a new Dicom with the same "SeriesInstanceUID" however, other UIDs can/must to remain the same. For example, _the <org root> "1.2.840.10008" is reserved for DICOM defined items_. 
I think that, if every time a new UID for this object is generated the code could be more flexible, in order to avoid loading issues because of having the same "SeriesInstanceUID".

**Comment by nbassler** [comment]
Oho:

```
from dicom import UID
UID.generate_uid()
'1.2.826.0.1.3680043.8.498.26830026147875277357188914'
UID.generate_uid(prefix="2.25.")
'2.25.2683002614787527731663738'
```

**Comment by nbassler** [comment]
Seems changing SeriesUID is not enough.

At Cube() top level class:
```
        meta.MediaStorageSOPClassUID = '1.2.840.10008.5.1.4.1.1.2'  # CT Image Storage
        meta.MediaStorageSOPInstanceUID = "1.2.3"
        meta.ImplementationClassUID = "1.2.3.4"
        meta.TransferSyntaxUID = UID.ImplicitVRLittleEndian  # Implicit VR Little Endian - Default Transfer Syntax
        ds = FileDataset("file", {}, file_meta=meta, preamble=b"\0" * 128)
        ds.PatientsName = self.patient_name
        ds.PatientID = "123456"
        ds.PatientsSex = '0'
        ds.PatientsBirthDate = '19010101'
        ds.SOPClassUID = '1.2.3'  # !!!!!!!!
        ds.SOPInstanceUID = '1.2.3'  # !!!!!!!!!!
        ds.StudyInstanceUID = '1.2.3'  # !!!!!!!!!!
        ds.FrameofReferenceUID = '1.2.3'  # !!!!!!!!!
        ds.SeriesInstanceUID = UID.generate_uid(prefix="2.25.")
```

at Ctx() level:
```
ds.SOPClassUID = '1.2.840.10008.5.1.4.1.1.2'  # CT Image Storage SOP Class
```

maybe we should address all of them

**Comment by grzanka** [comment]
What do you mean by "all of them" ?

'1.2.840.10008.5.1.4.1.1.2' is like a class name, it identifies type of data, not the object itself.
Visit http://www.dicomlibrary.com/dicom/sop/ and find there '1.2.840.10008.5.1.4.1.1.2'

**Comment by nbassler** [comment]
I dont know what they mean. I just see the "UID" string many places, succeeded by numbers which are hardcoded.

**Comment by grzanka** [comment]
Knowledge of DICOM standard is needed to understand them, but we may also add some comments to clarify the picture.

For each tag we should consult the DICOM manual, check if empty value is allowed, write some description what the tag means etc...

Some assignments are unclear: `   ds.PatientsSex = '0'` -> does 0 means woman or man ?
Does it need to be a string or it could be an integer ?
