### ISSUE TITLE
DICOM: long list of warnings when Eclipse is loading PyTRiP generated data

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#193]
(scroll to the right to see warnings)

missing attributes:

- [x] 'StudyID' (0020,0010)
- [x] 'ReferringPhysiciansName' (0008,0090)
- [x] 'PositionReferenceIndicator' (0020,1040)
- [x] 'SeriesNumber' (0020,0011)
- [x] 'KVP' (0018,0060)
- [x] 'AcquisitionNumber' (0020,0012)

```
Date                 Object                                                                                     Level      Category        Log Message
===================================================================================================================================================================================
11/27/2016 22:00:37  General                                                                                    Info       GENERAL         ReadFile                 : Reading DICOM Media File <C:\Users\IMPS\Documents\example_data\out\ct.0.dcm>
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Warning    Reading         |W| ImportId_CRmCTmRDmRImRSmREGmDREGmTPmTWmMRmPTmSCmRPmRNmRTmRXmUSm: Type 2 Attribute 'StudyID' (0020,0010) is missing in DICOM stream
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Warning    Reading         |W| ImportReferringPhysiciansName_CRmCTmRDmRImRSmREGmDREGmTPmTWmMRmPTmSCmRPmRNmRTmRXmUSm: Type 2 Attribute 'ReferringPhysiciansName' (0008,0090) is missing in DICOM stream
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Warning    Reading         |W| ImportPositionReferenceIndicator_CTmRDmRIuREGmDREGmTPuTWuMRmPTmRPuRNmUSm: Type 2 Attribute 'PositionReferenceIndicator' (0020,1040) is missing in DICOM stream
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Warning    Reading         |W| ImportSeriesNumber_CRmCTmREGmTPmTWmMRmPTmSCmUSm: Type 2 Attribute 'SeriesNumber' (0020,0011) is missing in DICOM stream
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Warning    Reading         |W| ImportManufacturer_CRmCTmRDmRImRSmREGmDREGmTPmTWmMRmPTmSCuRPmRNmRTmRXmUSm: Type 2 Attribute 'Manufacturer' (0008,0070) is missing in DICOM stream
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Warning    Reading         |W| ImportKVP_CTm            : Type 2 Attribute 'KVP' (0018,0060) is missing in DICOM stream
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Warning    Reading         |W| ImportAcquisitionNumber_CTm: Type 2 Attribute 'AcquisitionNumber' (0020,0012) is missing in DICOM stream
11/27/2016 22:00:37  2.16.1.113662.2.12.0.3057.1241703565.10                                                    Info       Reading         Import                   : DICOM conversion succeeded
11/27/2016 22:00:37  General                                                                                    Info       GENERAL         ReadFile                 : Reading DICOM Media File 
```
(repeated for each slice)

**Comment by grzanka** [comment]
This document might be useful in solving the issue:
https://infoscience.epfl.ch/record/133543/files/RTSTRUCT_Exporter.pdf

**Comment by nbassler** [comment]
looks rather simple, they just have to be added to ctx.py::create_dicom() ?

**Comment by grzanka** [comment]
yes, exactly

**Comment by nbassler** [comment]
https://imagej.nih.gov/nih-image/download/documents/dicom-dict.txt
http://dicomlookup.com/lookuppage.asp

**Comment by TokePrintz** [comment]
So, Alina and I put in the newly generated dcm4 files from Niels in Eclipse and it seemed to all work fine. We got a lot of warnings that seemed unimportant (you always get a lot of warnings) due to missing dicom-tags. 
Although, in the import/export module of Eclipse, in the list of ct slices, the order of the number of the slices was wrong: 1, 10, 100, 101, 102....., 110, 111, etc. This could have bothered Raystation when doing the import, if it looks at these numbers and not directly at slice position, which seems to be the case in Eclipse

**Comment by grzanka** [comment]
Can you explain a bit more about the order ? The sequence you provided in monotonically increasing - what exactly is the problem ?

**Comment by TokePrintz** [comment]
![dcm4](https://cloud.githubusercontent.com/assets/22157203/22712463/2cae92aa-ed85-11e6-9363-fcabeb9f80c0.png)

**Comment by nbassler** [comment]
Ah... Sorting by sting, not int val. I think I know where it is bad.

**Comment by grzanka** [comment]
@TokePrintz what is the naming of the slices in the patient data, when the slices are correctly loaded and sorted ?

**Comment by TokePrintz** [comment]
Here is the list of warnings. Sry for the screenshot solution. Couldn't seem to get a log file that looked transparent enough for an upload here. Ignore the ones with "connection not done. Object already exists"  - this is because I "reimported" the same CT set just to get the warnings again and do the screenshot. 
![dcm4errors](https://cloud.githubusercontent.com/assets/22157203/22713270/088b38ee-ed88-11e6-8cce-bb32350986fe.png)

@grzanka Not completely sure that I understand what you ask? The "correct" order would be 1,2,3,4,5... and so on up to the last slice. For Eclipse it was not an issue though that the slices were listed as in the attached picture. Alina assumes that it is because Eclipse reads the coordinates of the slices and lists them thereafter; therefore the 3D CT image was generated and looked fine.

**Comment by grzanka** [comment]
Thanks @TokePrintz , I will fix missing tags. 

More specifically - if you import correct DICOM file (i.e. patient CT ) - are slices called "Image 1", "Image 2" etc or in a different way ? Is "Image" string included in the name of slice ?

**Comment by asg16** [comment]
Hi Leszek! I think the name of the slices does not matter as much as the z coordinates of the slices to determine the order.... I think I need to provide us all with some examples of real, correct functioning dicom file tags and names (f ex. exported from Pinnacle) so that we have enough information to help us solve this task in a correct way in pytrip. I will try to do it tomorrow.....

**Comment by nbassler** [comment]
We have these examples:
https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/

dcm4.zip was made from TST001000.ctx which stems from a HIT ionplan dicom file.

**Comment by asg16** [comment]
I meant, when you convert to ctx/vdx (i.e. VOXELPLAN) files you strip your dicom files of all relevant tags, you need to analyse the structure of the information contained in dicom files exported from a "real", commercial TPS, to be able to produce again meaningful dicom files (that a "real" TPS can recognize as such) with pytrip out of your nude voxelplan files, that is what I meant.

**Comment by nbassler** [comment]
Yes, that is the issue. Our eclipse access is not easy. Raystation doesn't give logs. We may have a few other minor systems and inspection via Matlab and Pydicom of course comparing to full files. Ana is looking into this, and what you can provide from eclipse is very appreciated. Goal is that the generated dicom files can be loaded in major TPS without any additional hacking.

**Comment by TokePrintz** [comment]
So, I just imported the newest set of dcm4 from @grzanka and there were no warnings! :-) 

...however, there is still the issue that the system complains that the patient is the same as one already imported (this time it was literally the same as the new set of dcm4 had not been changed in that regard). I think it is because all generated dicoms have UID1 123456, which must be the unique UID related to the "name" of the patient....(is there an open issue for this somewhere?)

**Comment by grzanka** [comment]
Thanks @TokePrintz , could you please write back which UIDs you had in mind and which exactly value it was ? I'll try to debug it.

**Comment by nbassler** [comment]
```123456``` is not an UID but the ```ds.patientID```.
This would correspond to patient_name in TRiP .hed files. Aka ```tst001```.

What behaviour should be expected if it is not given on beforehand?

I suggest add a  ```patient_id``` option in the ```create_dicom()``` kind of classes. If not set, and if patient_name does not exist, it will fill with some random number. This ensures compability.

**Comment by TokePrintz** [comment]
![error_jet01](https://cloud.githubusercontent.com/assets/22157203/23229676/6be147e8-f941-11e6-9efb-f9ff8a77d302.png)
We got a couple of new warnings when importing the newly generated patient of #245. We did not get these warnings when importing the (latest of the) test files sent by Niels and Leszek.

**Comment by grzanka** [comment]
@TokePrintz I've created a new issue for these warnings
