### ISSUE TITLE
Eclipse recognizes every DICOM set generated by pytrip as the same patient 

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#254]
![matchingname](https://cloud.githubusercontent.com/assets/22157203/23229784/d77fc628-f941-11e6-8fb9-adab14037e9f.png)
Here Eclipse thinks that the pytrip-generated DICOM set of Alinas patient from #245  is the same as the test files sent by Leszek and Niels  in regard to #193 (which is clearly not the case).  
The patient ID1 is always 123456 for DICOM sets generated with pytrip. Therefore Eclipse thinks it is the same patient. This seems to happen no matter what the other UIDs say because clearly they are listed with different names ("tst002" vs "cube"), being the original names of the respective .hed file.

This issue makes it a bit difficult to joggle with more than one pytrip-generated DICOM set at a time, because you have to delete the existing patient first in order to import the new one.

**Comment by nbassler** [comment]
Propose this solution:

- add ```patient_id``` attribute to cube class.
- if ```patient_id``` is ```None``` when a new cube object is created, then put in a number  ```datetime.datetime.today().strftime('%Y%m%d-%H%M%S')```

or should we add a method like ```new_patient_id(string=id)``` , and if called with None it will be set to current timestamp?

I am not in favour of using a true random number. A real time stamp is sufficiently random and may even help working with pytrip files under different circumastances.

**Comment by nbassler** [comment]
@grzanka

**Comment by TokePrintz** [comment]
With a bleeding heart I am reopening this issue...because Eclipse still sees everything I feed it from pytrip as the same patient! It seems that I was wrong and that the Patient ID tag was not the issue (at least not the only one). Alina and I have since been trying dcmdump and -modify to see if we could pinpoint which tag(s) can be the problem, starting with tags that are hardcoded in PyTRiP but differ in two "raw" DICOM sets...but so far no cigar.
I was suspecting maybe SOPClassUID or SOPInstanceUID but having read #191, I am not so sure anymore...

**Comment by grzanka** [comment]
What about a filename ? If you change a filename to SOPInstanceUID ?

**Comment by asg16** [comment]
Found it: the tag 0020,000d, StudyInstanceUID, has to be different for each CT and RTS set. So far, pytrip is delivering all dicoms with a fixed tag, 1.2.3. 
This is the minimum change in your code so that we can upload different patients at the same time in Eclipse (not talking about rigorous DICOM tagging, but just to patch for our purposes now). We just wrote a different tag from "1.2.3", and it worked.

**Comment by grzanka** [comment]
@asg16 thanks, I am trying to implement it now and generate patient-specific UIDs.
Any hints on prefix that should be used ?

**Comment by asg16** [comment]
Just as an example, I found this page: http://www.oid-info.com/get/1.2.276.0.7230010
which explains very clearly that every number in the string has a meaning.
Knowing that the UIDs have a complex structure in which each number has a meaning, I think that we should stick to the simplest unique tags which work for us, for now, without copying the first string part which points to some institution, or software, or CT scanner, and therefore we are not allowed to use, and constitutes a protocol violation. 
So far, based on what you have done, I would propose, from my little knowledge on dicom:
1. The patient name and ID are ok as they are in my opinion. The patient name is determined by the name in the voxelplan header, and both the name and the patient ID can be changed while importing the data in Eclipse.
2. To modify the tag 0002,0003 (MediaStorageSOPInstanceUID) to make it unique for each CT slice, and identical to the tag 0008,0018 (SOPInstanceUID), as it should be. To create these tags, adding a slice counter is not enough, since the counter would be identical for different CT series. I would remove as I said the long fixed string that you add to the SOPInstanceUID, and create your own pytrip unique number.
3. To modify the tag 0020,000e (SeriesInstanceUID) with a unique number for each whole CT series
4. To modify the tag 0020,000d (StudyInstanceUID) with a unique number for each whole CT series
5. For the RTS, these four tags are changed in the same way for the structures (they also have to be unique), and additionally, you need to change accordingly all the ReferencedSOPInstanceUID to point at the right CT slice. For what I have seen, the RTReferencedSeriesSequence and RTReferencedStudySequence do not need to be filled with any values.
6. I could easily do checks of this in the weekend.

**Comment by asg16** [comment]
I mean, you can add a running number to each SOPInstanceUID for each slice, but the number before needs to be pytrip-specific, and unique.

**Comment by asg16** [comment]
For the CT dataset:
0020,000d = pytrip_unique_number1 for each CT dataset
0020,000e = pytrip_unique_number2 for each CT dataset
0002,0003 = 0008,0018 = pytrip_unique_number3.sliceNr for each CT slice
For the structures:
0020,000d = pytrip_unique_number4 for each RTStructure set
0020,000e = pytrip_unique_number5  for each RTStructure set
0002,0003 = 0008,0018 = pytrip_unique_number6  for each RTStructure set
each ReferencedSOPInstanceUID carries the right pytrip_unique_number3.sliceNr from above
and RTReferencedSeriesSequence and RTReferencedStudySequence do apparently not need to be filled with any values

**Comment by asg16** [comment]
Stack Exchange advice on how to create UIDs:
http://stackoverflow.com/questions/10295792/how-to-generate-sopinstance-uid-for-dicom-file

**Comment by grzanka** [comment]
@asg16 thanks for suggestions, I think that I'll prepare sth based on that.

Just one question. Looking at example data from slicer project. I see that StudyInstanceUID is the same for CT and RTStructures, while SeriesInstanceUID is different. Do you think it make sense ?

**Comment by asg16** [comment]
Yes, I just checked with dcmdump a CT series and RTStruct file from Eclipse, and the StudyInstanceUID is the same also for the structures. The SeriesInstanceUID is different as you say.
The SeriesInstanceUID of the CT is
(0020,000e) UI [2.16.840.1.113662.2.1.2428.224843.2101025.2091947.2514733.20] #  60, 1 SeriesInstanceUID
And when I do dcmdump and grep the SeriesInstanceUID of the Structures, I still find a reference to the SeriesInstanceUID of the CT, below:
(0020,000e) UI [1.2.246.352.71.2.201879207.133670.20101025152138] #  48, 1 SeriesInstanceUID
            (0020,000e) UI [2.16.840.1.113662.2.1.2428.224843.2101025.2091947.2514733.20] #  60, 1 SeriesInstanceUID

**Comment by asg16** [comment]
But I do not know how necessary the second line is.

**Comment by grzanka** [comment]
I've already implemented generation of Series and Study instance UIDs here:
https://github.com/pytrip/pytrip/pull/293/commits/9c09d6da0067fc5a515a1625203f6184ea288f07

These UIDs are set in `__init__` method or read from DICOM. 

I've used uuid based UIDs with prefix "2.25", using following approach:
```
>>> import dicom
>>> from dicom import UID
>>> UID.generate_uid(prefix=None)
'2.25.313839037860157675636391281123192372790'
>>> UID.generate_uid(prefix=None)
'2.25.314910383257561062003345708611941858870'
```

I do not see now the way to generate ISO based (prefixed with "1.") dedicated pytrip UIDs. Do you think its OK now ?

I still need to implement SOPInstanceUID generation and other tags

**Comment by grzanka** [comment]
Right now it works this way:

```

# grzanka at nz61-6 in ~/PycharmProjects/pytrip on git:feature/254-study-instance-uid ✖︎ [18:52:31]
→ dcmdump +P SOPInstanceUID +P StudyInstanceUID +P SeriesInstanceUID 2/CT.PYTRIP.100.dcm                                             ~/PycharmProjects/pytrip
(0008,0018) UI [2.25.180173472039715981188505532300678660196] #  44, 1 SOPInstanceUID
(0020,000d) UI [2.25.180173387265582090925664563059795066422] #  44, 1 StudyInstanceUID
(0020,000e) UI [2.25.180173443517577476053344254475999804982] #  44, 1 SeriesInstanceUID

# grzanka at nz61-6 in ~/PycharmProjects/pytrip on git:feature/254-study-instance-uid ✖︎ [18:52:35]
→ dcmdump +P SOPInstanceUID +P StudyInstanceUID +P SeriesInstanceUID 2/CT.PYTRIP.101.dcm                                             ~/PycharmProjects/pytrip
(0008,0018) UI [2.25.180173472039715981188505532300678660197] #  44, 1 SOPInstanceUID
(0020,000d) UI [2.25.180173387265582090925664563059795066422] #  44, 1 StudyInstanceUID
(0020,000e) UI [2.25.180173443517577476053344254475999804982] #  44, 1 SeriesInstanceUID

# grzanka at nz61-6 in ~/PycharmProjects/pytrip on git:feature/254-study-instance-uid ✖︎ [18:52:37]
→ dcmdump +P SOPInstanceUID +P StudyInstanceUID +P SeriesInstanceUID 2/RTSTRUCT.PYTRIP.dcm                                           ~/PycharmProjects/pytrip
(0008,0018) UI [2.25.180748990958190973335288922955139153462] #  44, 1 SOPInstanceUID
(0020,000d) UI [2.25.180173387265582090925664563059795066422] #  44, 1 StudyInstanceUID
(0020,000e) UI [2.25.180748963228334093342770765214756535862] #  44, 1 SeriesInstanceUID
(0020,000e) UI [2.25.180173443517577476053344254475999804982] #  44, 1 SeriesInstanceUID
```

See my modifications in PR #293

**Comment by asg16** [comment]
HI Leszek! It all seems reasonable to me! Both the prefix, 2.25, and the part with the unique numbers, which in the case of the SOPInstanceUID shows a last running number for each CT slice. And we saw in the code that you make the MediaStorageSOPInstanceUID equal to the SOPInstanceUID, so that is also correct! 
If you send me two datasets generated with these corrections I can test tomorrow the import in Eclipse.

**Comment by asg16** [comment]
To generate ISO based UIDs, for what I have read today, you need to request an OID identifier for your institution, which might be a bit too much for now.

**Comment by grzanka** [comment]
I did some tests on two data samples from slicer database (DICOM -> TRIP98 -> DICOM). Please find the samples here: 
https://cernbox.cern.ch/index.php/s/d15LdVEnmOUtCTt
https://cernbox.cern.ch/index.php/s/IGy3XjMhpVzhzn3

**Comment by TokePrintz** [comment]
We can hereby confirm that all the changes work! I would say this is a great enhancement and that we have now reached a version supporting import-export of DICOM in Eclipse in a satisfactory manner!:-) Hope it will function for other TPSs too...

**Comment by grzanka** [comment]
Can you squash merge last Pr?

04.03.2017 10:20 "TokePrintz" <notifications@github.com> napisał(a):

**Comment by grzanka** [comment]
Thanks. I will make a new release later. On android it is not easy.

I am glad it works with Eclipse!

04.03.2017 11:17 "TokePrintz" <notifications@github.com> napisał(a):

**Comment by asg16** [comment]
im also happy it works! Good work! :-)
